export const categories = [
  { value: "ai", label: "Artificial Intelligence" },
  { value: "react", label: "React" },
  { value: "rails", label: "Ruby on Rails" },
  { value: "nextjs", label: "Next.js" },
  { value: "python", label: "Python" },
  { value: "javascript", label: "Javascript" },
  { value: "html", label: "HTML & Frontend" },
  { value: "css", label: "CSS" },
  { value: "css tricks", label: "CSS Tricks" },
  { value: "caching", label: "Caching" },
  { value: "backend", label: "Database & Designs" },
  { value: "auth", label: "Authentication & Security" },
  { value: "host", label: "Web Hosting" },
  { value: "technology", label: "Technology" },
];

export const options = [
  "ai",
  "ai regulation",
  "backend",
  "beginner",
  "beginners",
  "caching",
  "chatgpt",
  "context api",
  "censorship",
  "css",
  "css-frameworks",
  "css tricks",
  "data flow",
  "deep-fakes",
  "developers",
  "dishonesty",
  "education",
  "fetch",
  "fonts",
  "frontend",
  "front-end",
  "gemini",
  "governments",
  "html",
  "javascript",
  "jobs",
  "jwt",
  "node",
  "nextjs",
  "otp",
  "postgresql",
  "prisma",
  "programming",
  "react",
  "recaptcha",
  "rendering",
  "ruby",
  "ruby on rails",
  "security",
  "server",
  "server-actions",
  "typography",
  "vercel",
  "video-generation",
  "web dev",
  "web service",
];

export const codeSampleLanguages = [
  { text: "HTML/XML", value: "haml" },
  { text: "JavaScript", value: "javascript" },
  { text: "TypeScript", value: "typescript" },
  { text: "Json", value: "json" },
  { text: "CSS", value: "css" },
  { text: "Bash", value: "bash" },
  { text: "PHP", value: "php" },
  { text: "Ruby", value: "ruby" },
  { text: "Python", value: "python" },
  { text: "Java", value: "java" },
  { text: "C", value: "c" },
  { text: "C#", value: "csharp" },
  { text: "C++", value: "cpp" },
  { text: "Go", value: "go" },
  { text: "Kotlin", value: "kotlin" },
  { text: "Markdown", value: "markdown" },
  { text: "PowerShell", value: "powershell" },
  { text: "SQL", value: "sql" },
  { text: "Swift", value: "swift" },
  { text: "YAML", value: "yaml" },
];
