export const categories = [
  { value: "all", label: "All" },
  { value: "ai", label: "Artificial Intelligence" },
  { value: "beginners", label: "Beginners" },
  { value: "react", label: "React" },
  { value: "web", label: "Web Development" },
  { value: "programming", label: "Programming" },
  { value: "backend", label: "Backend & APIs" },
  { value: "web workers", label: "Architecture" },
  { value: "typography", label: "Typography" },
  { value: "ruby/rails", label: "Ruby on Rails" },
  { value: "nextjs", label: "Next.js" },
  { value: "remix", label: "Remix" },
  { value: "tailwind", label: "Tailwind CSS" },
  { value: "webdev", label: "Web Development" },
  { value: "python", label: "Python" },
  { value: "javascript", label: "Javascript" },
  { value: "typescript", label: "Typescript" },
  { value: "html", label: "HTML & Frontend" },
  { value: "css", label: "CSS" },
  { value: "ui/ux", label: "UX/UI" },
  { value: "caching", label: "Caching" },
  { value: "auth", label: "Authentication & Security" },
  { value: "law", label: "Law & Ethics" },
  { value: "host", label: "Web Hosting" },
  { value: "jwt", label: "Web Security" },
  { value: "technology", label: "Technology" },
  { value: "api", label: "API Development" },
  { value: "nodejs", label: "Node Js" },
  { value: "frontend", label: "Frontend" },
  { value: "prisma", label: "Prisma" },
];
//TODO: schedule a cron job to do this after every two days
// tag → canonical category (anchor tag)
// export const tagCategoryMap: Record<string, string> = {
//   // --- AI ---
//   ai: "ai",
//   "artificial intelligence": "ai",
//   "ai regulation": "ai",
//   "ai video": "ai",
//   chatgpt: "ai",
//   gemini: "ai",
//   "machine learning": "ai, ml, python",

//   // --- Web Development ---
//   webdev: "webdev",
//   "web dev": "webdev",
//   "web development": "webdev",
//   "web-development": "webdev",
//   "web-dev": "webdev",
//   frontend: "webdev",
//   fronted: "webdev",
//   html: "webdev",
//   css: "webdev",
//   "css tricks": "webdev",
//   "css-frameworks": "webdev",
//   javascript: "webdev",
//   typescript: "webdev",
//   react: "webdev",
//   nextjs: "webdev",
//   remix: "webdev",
//   tailwind: "webdev",
//   rendering: "webdev",
//   "ui/ux": "webdev",
//   typography: "webdev",
//   fonts: "webdev",
//   forms: "webdev",
//   "context api": "webdev",
//   "web service": "webdev",
//   "web workers": "webdev",

//   // --- Backend & APIs ---
//   backend: "backend",
//   node: "backend",
//   nodejs: "backend",
//   database: "backend",
//   postgresql: "backend",
//   prisma: "backend",
//   "rails api": "backend",
//   "ruby on rails": "backend",
//   "rest api": "backend",
//   "api development": "backend",
//   server: "backend",
//   "server-actions": "backend",
//   revalidate: "backend",
//   root: "backend",
//   hosting: "backend",
//   vercel: "backend",
//   saas: "backend",
//   caching: "backend",
//   "cron jobs": "backend",

//   // --- Programming & Languages ---
//   programming: "programming",
//   coding: "programming",
//   "vibe coding": "programming",
//   resources: "programming",
//   tools: "programming",
//   git: "programming",
//   github: "programming",
//   githubactions: "programming",
//   python: "programming",
//   ruby: "programming",
//   "c++": "programming",
//   algorithms: "programming",
//   markdown: "programming",
//   jobs: "programming",
//   tutorials: "programming",
//   "best practices": "programming",
//   developers: "programming",

//   // --- Security & Authentication ---
//   security: "security",
//   authentication: "security",
//   auth: "security",
//   jwt: "security",
//   sso: "security",
//   otp: "security",
//   recaptcha: "security",
//   "data safety": "security",

//   // --- Technology & Future ---
//   technology: "technology",
//   trending: "technology",
//   future: "technology",
//   innovation: "technology",
//   "quantum computing": "technology",

//   // --- Law & Governance ---
//   law: "law",
//   "legal issues": "law",
//   governments: "law",
//   censorship: "law",
//   crime: "law",
//   investigation: "law",
//   dishonesty: "law",
//   technophobia: "law",
//   education: "law",

//   // --- Beginners ---
//   beginners: "beginners",
//   beginner: "beginners",
//   // --- Beginners ---
//   machine: "machine learning",
//   "python programming": "python/machine learning",
// };
export const tagCategoryMap: Record<string, string> = {
  // --- AI & Machine Learning ---
  ai: "ai",
  "ai regulation": "ai",
  "ai video": "ai",
  "ai videos": "ai",
  "artificial intelligence": "ai",
  chatgpt: "ai",
  "data science": "ai",
  deepfakes: "ai",
  gemini: "ai",
  "machine learning": "ai",

  // --- Web Development (Frontend) ---
  webdev: "webdev",
  "web dev": "webdev",
  "web development": "webdev",
  "web-dev": "webdev",
  "context api": "webdev",
  css: "webdev",
  "css frameworks": "webdev",
  "css tricks": "webdev",
  design: "webdev",
  fetch: "webdev",
  fonts: "webdev",
  forms: "webdev",
  frontend: "webdev",
  html: "webdev",
  javascript: "webdev",
  nextjs: "webdev",
  react: "webdev",
  "react-router": "webdev",
  remix: "webdev",
  rendering: "webdev",
  tailwind: "webdev",
  "tanstack-router": "webdev",
  typescript: "webdev",
  typography: "webdev",
  "ui/ux": "webdev",
  "web service": "webdev",
  "web workers": "webdev",

  // --- Backend & APIs ---
  backend: "backend",
  "api development": "backend",
  caching: "backend",
  "cron jobs": "backend",
  database: "backend",
  drizzle: "backend",
  emails: "backend",
  hosting: "backend",
  node: "backend",
  nodejs: "backend",
  postgresql: "backend",
  prisma: "backend",
  "rails api": "backend",
  "rest api": "backend",
  revalidate: "backend",
  root: "backend",
  "ruby on rails": "backend",
  saas: "backend",
  server: "backend",
  "server actions": "backend",
  serverless: "backend",
  vercel: "backend",

  // --- Programming & Languages ---
  programming: "programming",
  algorithms: "programming",
  "best practices": "programming",
  "c++": "programming",
  coding: "programming",
  "data flow": "programming",
  developers: "programming",
  git: "programming",
  github: "programming",
  githubactions: "programming",
  jobs: "programming",
  markdown: "programming",
  python: "programming",
  resources: "programming",
  ruby: "programming",
  rust: "programming",
  tools: "programming",
  tauri: "programming",
  tutorials: "programming",
  "vibe coding": "programming",

  // --- Security & Authentication ---
  security: "security",
  authentication: "security",
  "better-auth": "security",
  "data safety": "security",
  jwe: "security",
  jwt: "security",
  "magic-link": "security",
  otp: "security",
  recaptcha: "security",
  safety: "security",
  sso: "security",

  // --- Technology & Future ---
  technology: "technology",
  android: "technology",
  "cloud computing": "technology",
  future: "technology",
  innovation: "technology",
  "quantum computing": "technology",
  trending: "technology",

  // --- Law, Governance & Society ---
  law: "law",
  censorship: "law",
  crime: "law",
  dishonesty: "law",
  education: "law",
  employment: "law",
  investigation: "law",
  "legal issues": "law",
  regulation: "law",
  technophobia: "law",

  // --- Testing & Performance ---
  "load testing": "testing",
  "performance testing": "testing",
  testing: "development",

  // --- Beginners ---
  beginner: "beginners",
  beginners: "beginners",
};
export const codeSampleLanguages = [
  { text: "HTML/XML", value: "haml" },
  { text: "Javascript", value: "javascript" },
  { text: "React (JSX)", value: "jsx" },
  { text: "TypeScript", value: "typescript" },
  { text: "React (TSX)", value: "tsx" },
  { text: "Json", value: "json" },
  { text: "CSS", value: "css" },
  { text: "Bash", value: "bash" },
  { text: "PHP", value: "php" },
  { text: "Ruby", value: "ruby" },
  { text: "Python", value: "python" },
  { text: "Java", value: "java" },
  { text: "C", value: "c" },
  { text: "C#", value: "csharp" },
  { text: "C++", value: "cpp" },
  { text: "Go", value: "go" },
  { text: "Kotlin", value: "kotlin" },
  { text: "Markdown", value: "markdown" },
  { text: "PowerShell", value: "powershell" },
  { text: "SQL", value: "sql" },
  { text: "Swift", value: "swift" },
  { text: "YAML", value: "yaml" },
];
