export const categories = [
  { value: "all", label: "All" },
  { value: "ai", label: "Artificial Intelligence" },
  { value: "beginners", label: "Beginners" },
  { value: "react", label: "React" },
  { value: "web", label: "Web Development" },
  { value: "programming", label: "Programming" },
  { value: "backend", label: "Databases" },
  { value: "multithreading", label: "Architecture" },
  { value: "typography", label: "Typography" },
  { value: "rails", label: "Ruby on Rails" },
  { value: "nextjs", label: "Next.js" },
  { value: "python", label: "Python" },
  { value: "javascript", label: "Javascript" },
  { value: "typescript", label: "Typescript" },
  { value: "html", label: "HTML & Frontend" },
  { value: "css", label: "CSS" },
  { value: "css tricks", label: "UX/UI" },
  { value: "caching", label: "Caching" },
  { value: "auth", label: "Authentication & Security" },
  { value: "host", label: "Web Hosting" },
  { value: "jwt", label: "Web Security" },
  { value: "technology", label: "Technology" },
  { value: "api", label: "API Development" },
  { value: "ai regulation", label: "AI regulation" },
  { value: "nodejs", label: "Node Js" },
  { value: "frontend", label: "Frontend" },
  { value: "prisma", label: "Prisma" },
];

export const options = [
  "ai",
  "ai regulation",
  "ai videos",
  "api development",
  "authentication",
  "backend",
  "beginner",
  "beginners",
  "c++",
  "caching",
  "censorship",
  "chatgpt",
  "context api",
  "crime",
  "css",
  "css tricks",
  "css-frameworks",
  "data flow",
  "developers",
  "dishonesty",
  "education",
  "fetch",
  "fonts",
  "forms",
  "front-end",
  "frontend",
  "future",
  "gemini",
  "governments",
  "hosting",
  "html",
  "innovation",
  "javascript",
  "jobs",
  "justice",
  "jwt",
  "multithreading",
  "nextjs",
  "node",
  "nodejs",
  "otp",
  "performance optimization",
  "postgresql",
  "prisma",
  "programming",
  "programming languages",
  "python",
  "quantum computing",
  "rails api",
  "react",
  "recaptcha",
  "rendering",
  "resources",
  "rest api",
  "revalidate",
  "ruby",
  "ruby on rails",
  "security",
  "server",
  "server-actions",
  "technology",
  "typescript",
  "typography",
  "vercel",
  "web dev",
  "web development",
  "web service",
  "web workers",
  "web-dev",
  "webdev",
];

export const codeSampleLanguages = [
  { text: "HTML/XML", value: "haml" },
  { text: "Javascript", value: "javascript" },
  { text: "React (JSX)", value: "jsx" },
  { text: "TypeScript", value: "typescript" },
  { text: "React (TSX)", value: "tsx" },
  { text: "Json", value: "json" },
  { text: "CSS", value: "css" },
  { text: "Bash", value: "bash" },
  { text: "PHP", value: "php" },
  { text: "Ruby", value: "ruby" },
  { text: "Python", value: "python" },
  { text: "Java", value: "java" },
  { text: "C", value: "c" },
  { text: "C#", value: "csharp" },
  { text: "C++", value: "cpp" },
  { text: "Go", value: "go" },
  { text: "Kotlin", value: "kotlin" },
  { text: "Markdown", value: "markdown" },
  { text: "PowerShell", value: "powershell" },
  { text: "SQL", value: "sql" },
  { text: "Swift", value: "swift" },
  { text: "YAML", value: "yaml" },
];
