export const categories = [
  { value: "ai", label: "Artificial Intelligence" },
  { value: "react", label: "React" },
  { value: "rails", label: "Ruby on Rails" },
  { value: "nextjs", label: "Next.js" },
  { value: "python", label: "Python" },
  { value: "javascript", label: "Javascript" },
  { value: "html", label: "HTML & Frontend" },
  { value: "css", label: "CSS" },
  { value: "css tricks", label: "CSS Tricks" },
  { value: "caching", label: "Caching" },
  { value: "database", label: "Database & Designs" },
  { value: "auth", label: "Authentication & Security" },
  { value: "host", label: "Web Hosting" },
  { value: "technology", label: "Technology" },
];
